name: bts_webview
description: A new Flutter package.
version: 0.0.2
author: RBS
homepage: https://github.com/robialta/bts_webview

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  webview_flutter: ^0.3.15+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
